"use client";

import React, { useEffect, useState } from "react";
import { evidence } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { AlertTriangle, CheckCircle2, Printer } from "lucide-react";

export default function EvidenceReportPage({ params }: { params: Promise<{ id: string }> }) {
  const unwrappedParams = React.use(params);
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    evidence.get(unwrappedParams.id).then(res => {
        setData(res.data);
        setLoading(false);
    }).catch(err => {
        console.error(err);
        setLoading(false);
    });
  }, [unwrappedParams.id]);

  if (loading) return <div className="p-8">Loading Report...</div>;
  if (!data) return <div className="p-8">Evidence not found</div>;

  const isCompliant = data.gaps?.[0]?.status === 'COMPLIANT';

  return (
    <div className="max-w-4xl mx-auto p-8 bg-white text-black min-h-screen font-serif print:p-0">
        {/* PRINT ACTIONS (Hidden in Print) */}
        <div className="flex justify-end items-center mb-8 print:hidden">
            <Button onClick={() => window.print()} className="gap-2 bg-black text-white hover:bg-gray-800">
                <Printer className="h-4 w-4" /> Print / Save as PDF
            </Button>
        </div>

        {/* PRINT HEADER */}
        <div className="border-b-2 border-black pb-8 mb-8 flex justify-between items-end">
             <div>
                 <h1 className="text-4xl font-bold tracking-widest text-black mb-2">AUDIT EVIDENCE</h1>
                 <p className="text-sm text-gray-600">Generated by Kivvat Compliance Engine</p>
             </div>
             <div className="text-right">
                 <p className="text-sm font-mono">ID: {data.id.split('-')[0]}</p>
                 <p className="text-sm font-mono">{new Date(data.timestamp).toLocaleString()}</p>
             </div>
        </div>

        {/* EVIDENCE SUMMARY */}
        <div className="grid grid-cols-2 gap-8 mb-12">
            <div>
                <h3 className="text-sm font-bold border-b border-gray-300 pb-2 mb-4">CONTROL INFORMATION</h3>
                <div className="space-y-4">
                     <div>
                         <span className="block text-xs text-gray-500">STANDARD</span>
                         <span className="font-semibold">{data.gaps?.[0]?.control?.standard?.name || 'Unknown User'}</span> 
                     </div>
                     <div>
                         <span className="block text-xs text-gray-500">CONTROL CODE</span>
                         <span className="font-semibold text-xl">{data.gaps?.[0]?.control?.code}</span>
                     </div>
                     <div>
                         <span className="block text-xs text-gray-500">CONTROL NAME</span>
                         <span>{data.gaps?.[0]?.control?.name}</span>
                     </div>
                </div>
            </div>

            <div>
                 <h3 className="text-sm font-bold border-b border-gray-300 pb-2 mb-4">VERIFICATION RESULT</h3>
                 <div className={`p-6 border-2 ${isCompliant ? 'border-emerald-600 bg-emerald-50' : 'border-red-600 bg-red-50'}`}>
                      <div className="flex items-center gap-4 mb-2">
                          {isCompliant ? <CheckCircle2 className="h-8 w-8 text-emerald-600" /> : <AlertTriangle className="h-8 w-8 text-red-600" />}
                          <span className={`text-2xl font-bold ${isCompliant ? 'text-emerald-900' : 'text-red-900'}`}>
                              {isCompliant ? 'PASS' : 'FAIL'}
                          </span>
                      </div>
                      <p className="text-sm text-gray-700">
                          {data.gaps?.[0]?.details || 'No details provided.'}
                      </p>
                 </div>
            </div>
        </div>

        {/* RAW DATA */}
        <div className="mb-8">
            <h3 className="text-sm font-bold border-b border-gray-300 pb-2 mb-4">TECHNICAL PROOF (RAW API OUTPUT)</h3>
            <div className="bg-gray-100 p-4 border border-gray-200 rounded font-mono text-xs overflow-x-auto">
                <pre>{JSON.stringify(data.result, null, 2)}</pre>
            </div>
        </div>

        {/* FOOTER */}
        <div className="mt-16 pt-8 border-t border-gray-200 text-center text-xs text-gray-400">
            <p>This document is digitally generated and serves as technical evidence for audit purposes.</p>
            <p>Kivvat Cloud Security • {new Date().getFullYear()}</p>
        </div>
    </div>
  );
}
